# Generated by Django 4.0.1 on 2022-01-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_travelling_monday_star'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelling_monday',
            name='tags',
        ),
        migrations.DeleteModel(
            name='STAR',
        ),
        migrations.DeleteModel(
            name='Travelling_Monday',
        ),
    ]
